# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Index',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='text',
            new_name='note',
        ),
    ]
