# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0002_auto_20171024_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Page',
        ),
    ]
