# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0005_auto_20171025_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='service_one',
            field=models.TextField(default='Sin Texto'),
        ),
        migrations.AddField(
            model_name='page',
            name='service_two',
            field=models.TextField(default='Sin Texto'),
        ),
    ]
