# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0006_auto_20171025_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='us_jpg1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
