# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0008_auto_20171026_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='us_jpg1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='us_jpg2',
        ),
        migrations.AddField(
            model_name='page',
            name='service_img',
            field=models.ImageField(default='services.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='page',
            name='us_img1',
            field=models.ImageField(default='us_img1.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='page',
            name='us_img2',
            field=models.ImageField(default='us_img2.png', upload_to=''),
        ),
    ]
