# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0009_auto_20171026_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='reference',
            field=models.TextField(default='Sin Texto'),
        ),
    ]
