# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0010_page_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='reference',
            new_name='reference_one',
        ),
        migrations.AddField(
            model_name='page',
            name='reference_tree',
            field=models.TextField(default='Sin Texto'),
        ),
        migrations.AddField(
            model_name='page',
            name='reference_two',
            field=models.TextField(default='Sin Texto'),
        ),
    ]
