# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0011_auto_20171026_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='phone_one',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='page',
            name='phone_two',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
