# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0012_auto_20171028_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('prevision', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='phone_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='phone_two',
            field=models.IntegerField(default=0),
        ),
    ]
