# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module_Start', '0013_auto_20171028_0124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Contact',
        ),
    ]
